[ART-1188] publish rpms to mirror
openshift/aos-cd-jobs pull request #2409
Opened 2020-11-06 08:30 UTC by Ximinhan

Automate publishing rpms to mirror, every time a new pre-release accepted update latest RHEL 7 worker RPMs on mirror.

2020-11-09 06:52 UTC, vfreex requested changes

2020-11-09 06:52 UTC, vfreex commented on scheduled-jobs/build/poll-payload/Jenkinsfile
> +def publishLatestRpms(String buildVersion) {
Scheduled jobs are meant to schedule other jobs instead of do the actual work itself. Could you move this part to a separate job?

2020-11-09 06:52 UTC, vfreex commented on scheduled-jobs/build/poll-payload/Jenkinsfile
> +    scripts_dir = "${env.WORKSPACE}/rhel-7-deps-mirroring/collect-deps.sh"
Where is this script?

2020-11-17 01:35 UTC, sosiouxme requested changes
Can there be a README for the new job based on https://github.com/openshift/aos-cd-jobs/blob/master/jobs/README.md#job-documentation-template

Be sure to try out the new job in a hackspace.

2020-11-17 01:35 UTC, sosiouxme commented on jobs/build/publish-rpms/Jenkinsfile
> +    commonlib.checkMock()
you need `commonlib.mockParam()` above in the params too or this will always fail.

2020-11-17 01:35 UTC, sosiouxme commented on jobs/build/publish-rpms/Jenkinsfile
> +    scripts_dir = "${env.WORKSPACE}/hacks/rhel-7-deps-mirroring/collect-deps.sh"
shouldn't this be... the directory?
```suggestion
    scripts_dir = "${env.WORKSPACE}/hacks/rhel-7-deps-mirroring/"
```
also i would rather the script be under the job, not sourced from somewhere we might change without realizing it's used here.

2020-11-17 01:35 UTC, sosiouxme commented on jobs/build/publish-rpms/Jenkinsfile
> +        sh "ssh use-mirror-upload 'createrepo --database $mirror_dir;/usr/local/bin/push.pub.sh openshift-v4/dependencies/rpms/${version}-beta -v'"
use commonlib.shell and one giant string. also take out the unprintable unicode...
```suggestion
        commonlib.shell """
            collect-deps.sh ${version}
            rm -rf /srv/pub/openshift-v4/dependencies/rpms/${version}-beta/*
            scp -r ${version}-beta/ use-mirror-upload:${mirror_dir}
            ssh use-mirror-upload 'createrepo --database ${mirror_dir};/usr/local/bin/push.pub.sh openshift-v4/dependencies/rpms/${version}-beta -v'
        """
```

2020-11-17 01:35 UTC, sosiouxme commented on jobs/build/publish-rpms/Jenkinsfile
> +￼       sh "rm -rf /srv/pub/openshift-v4/dependencies/rpms/${version}-beta/*"
this should run on `use-mirror-upload`, right? not buildvm

2020-11-17 01:35 UTC, sosiouxme commented on scheduled-jobs/build/poll-payload/Jenkinsfile
> +            build(
can this be restricted to just the x86_64 releases? we only want to sync rpms for accepted x86_64 releases.

2020-11-18 10:39 UTC, closed without merging