[ART-2353] Clean metadata advisory before attaching builds
openshift/aos-cd-jobs pull request #2426
Opened 2020-11-18 11:39 UTC by thiagoalessio

To avoid a mix of `.stage` and `.prod` builds in the same advisory.

2020-11-19 10:44 UTC, joepvd requested changes
If only a single operator needs to get rebuilt and attached, now all others will get removed. Not sure that's the behavior I'd expect.

2020-11-19 14:00 UTC, vfreex requested changes

2020-11-19 14:00 UTC, vfreex commented on jobs/build/appregistry/appregistry.groovy
> +    cleanAdvisoryBuilds(params.METADATA_ADVISORY)
As @joepvd mentioned, if we only rebuild specific metadatas, this is going to remove all metadata builds. Would like to have a smarter way (e.g. filter by environment name then remove them with elliott)

2020-11-19 14:35 UTC, vfreex commented on jobs/build/appregistry/appregistry.groovy
> +    cleanAdvisoryBuilds(params.METADATA_ADVISORY)
Or a simple approach: add an option to opt out this behavior if checked.

2020-12-11 14:58 UTC, thiagoalessio commented
Thanks @vfreex and @joepvd for the review! I changed the strategy: I list all currently attached builds, and remove _only_ the ones that don't have the current `STREAM` on its NVR.
So, if we are running it with `STREAM=prod`, it would remove all builds that have no `".prod"` on the NVR.

2020-12-21 22:56 UTC, sosiouxme approved these changes
nice

2020-12-21 22:56 UTC, merged