[ART-2807] Ask build type when ocp4 is manually triggered
openshift/aos-cd-jobs pull request #2591
Opened 2021-04-23 12:37 UTC by thiagoalessio

2021-04-28 04:41 UTC, sosiouxme requested changes
what about the `custom` job? maybe logic can be extracted into buildlib.

ugh, `ocp4` still has no `README`. `custom` does though.

2021-04-28 04:41 UTC, sosiouxme commented on jobs/build/ocp4/build.groovy
> +    if (!isTriggeredByOrganicLifeForms()) {
:rofl:

2021-04-28 04:41 UTC, sosiouxme commented on jobs/build/ocp4/build.groovy
> +    askBuildType()
should not do this if hooman checked the `SCRATCH` option; only "are you sure" on prod builds.

2021-04-28 04:41 UTC, sosiouxme commented on jobs/build/ocp4/build.groovy
> +    }.contains('UserIdCause')
buildlib.isBuildPermitted just checks that there's a real user that kicked off the request. i don't know which is the "best" way but it seems like they ought to work the same...

2021-05-10 13:54 UTC, thiagoalessio commented
> what about the `custom` job? maybe logic can be extracted into buildlib.
done:
- extracted logic to buildlib: https://github.com/openshift/aos-cd-jobs/pull/2591/commits/30f95056f97b8a702ff9289d3329cc27c31863d0
- use it on custom job too: https://github.com/openshift/aos-cd-jobs/pull/2591/commits/478bc81c0b928e9370a2796f2f24a2e9c8ed7adc

2021-05-10 13:55 UTC, thiagoalessio commented
> ugh, ocp4 still has no README. custom does though.

no problem, writing one now ...

2021-05-18 05:32 UTC, vfreex requested changes
Some minor issues otherwise LGTM.

2021-05-18 05:32 UTC, vfreex commented on pipeline-scripts/buildlib.groovy
> +        scratch = false
I am concerned about the use of global variable `scratch` here. People have to remember to define this global variable when calling from a Jenkinsfile. I would suggest returning this value instead.

Also the function name `setBuildType` sounds confusing. Would prefer a name more specific like `getBuildPurpose` `shouldSkipTag` or something.

2021-05-18 05:32 UTC, vfreex commented on pipeline-scripts/buildlib.groovy
> +def askBuildType() {
Same here, would prefer a name more specific like `askBuildPurpose` `askSkipTag` or something.

2021-08-04 12:33 UTC, joepvd commented
I think this approach has become obsolete with the concept of assemblies: https://issues.redhat.com/projects/ART/issues/ART-2924. Can we close this, @thiagoalessio?

2021-08-31 14:53 UTC, thiagoalessio commented
yeah, obsolete @joepvd ! closing it now

2021-08-31 14:53 UTC, closed without merging