Sync rhcos for pre-releases in promote
openshift/aos-cd-jobs pull request #2621
Opened 2021-05-14 21:43 UTC by thegreyd

2021-05-18 06:06 UTC, vfreex requested changes
The arch suffix doesn't seem right. Otherwise LGTM!

2021-05-18 21:26 UTC, thegreyd commented on jobs/build/promote/Jenkinsfile
> +    is_prerelease = false
"is_fc_or_rc" ?

2021-05-18 21:28 UTC, thegreyd commented on jobs/build/promote/Jenkinsfile
> +                alt_arch = arch == "x86_64"? "" : arch
hah thanks for catching that. it would've failed for other arches

2021-05-19 07:57 UTC, vfreex approved these changes
/lgtm

2021-05-19 07:57 UTC, vfreex commented on jobs/build/promote/Jenkinsfile
> +    is_prerelease = false
Or use 2 separate variables. It is not a strong opinion... Just feel the name `prerelease` ambiguous XD

2021-05-20 09:51 UTC, thiagoalessio approved these changes
/lgtm

2021-05-21 02:16 UTC, merged