[ART-2682] Verify flaw bugs are attached and associated with specific…
openshift/aos-cd-jobs pull request #2796
Opened 2021-10-21 11:19 UTC by vfreex

… builds

Requires https://github.com/openshift/elliott/pull/239

2022-01-25 09:27 UTC, joepvd requested changes
This would need to be incorporated in `promote-assembly`...

2022-02-14 06:45 UTC, vfreex commented
@joepvd PR has been updated to be incorporated in promote-assembly.

2022-02-14 09:22 UTC, joepvd commented
/lgtm

2022-02-14 09:28 UTC, joepvd approved these changes

2022-02-15 04:48 UTC, merged