Create check-rhcos
openshift/aos-cd-jobs pull request #3069
Opened 2022-05-20 15:41 UTC by joepvd

This is a monitoring job that is intended to be run on a schedule, and
to post to slack an image of a table of the results of rhcos pipelines.

2022-05-23 16:50 UTC, locriandev requested changes

2022-05-23 16:50 UTC, locriandev commented on pyartcd/pyartcd/pipelines/report_rhcos.py
> +        self.rhcos_urls = {
The 3 fields above are read-only constants, could be moved outside the class definition (better if renamed in capital letters)

2022-05-23 16:50 UTC, locriandev commented on pyartcd/pyartcd/pipelines/report_rhcos.py
> +            if arch == 'arm64' and int(version.split('.')[-1]) < 9:
A comment would be appreciated :) even if I can tell "arm is not applicable for OCP < 4.9)

2022-05-23 16:50 UTC, locriandev commented on pyartcd/pyartcd/pipelines/report_rhcos.py
> +            if complete_id == good_id:
'good_id' might be referenced before assignment

2022-05-23 16:50 UTC, locriandev commented on pyartcd/pyartcd/pipelines/report_rhcos.py
> +        header = "<td></td>"
HTML rendering could be simplified by using a template engine, e.g. [Jinja](https://jinja.palletsprojects.com/en/3.1.x/)

2022-05-23 16:50 UTC, locriandev commented on pyartcd/pyartcd/pipelines/report_rhcos.py
> +    async def get_data_for_arch(self, arch):
Does this really need to be async? Can't find no signs of 'await'

2022-05-23 16:50 UTC, locriandev commented on scheduled-jobs/build/check-rhcos/Jenkinsfile
> +        job: '../aos-cd-builds/build%2Fcheck-bugs',
Wrong called job :)

2022-05-23 16:50 UTC, locriandev commented on jobs/build/check-rhcos/Jenkinsfile
> +    // Check bugs
// Check RHCOS

2022-05-24 14:12 UTC, sosiouxme commented
Couple thoughts:

1. since you're generating html already, how about passing that back up to the job and making it the job's description? then we can just go through job status pages to see trends over time.
1. probably best to run this daily in early AM, but maybe only spam the channel on Mon/Tue/Wed?

2022-07-25 09:27 UTC, merged