Use release_date from assembly definition if present
openshift/aos-cd-jobs pull request #3157
Opened 2022-07-29 20:01 UTC by thegreyd

Goes with https://github.com/openshift/doozer/pull/626

2022-07-31 16:10 UTC, ashwindasr requested changes

2022-07-31 16:10 UTC, ashwindasr commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +        if not (advisories or jira_issue_key or self.release_date):
Just to confirm, we are returning `False` only if all 3 values, `advisories`, `jira_issue_key` and `self.release_date `are None/Empty?

2022-08-03 06:14 UTC, vfreex requested changes

2022-08-03 06:14 UTC, vfreex commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +        self.update_advisory_release_date()
No need to call this function if the advisories are just created.

2022-08-03 06:14 UTC, vfreex commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +@click.option("--date", metavar="YYYY-Mon-DD", required=False,
I think we shouldn't allow users to specify release date with `--data` anymore if it is already defined in releases.yml. Would like to completely remove this option.

2023-01-01 08:01 UTC, closed without merging