add greenwave check
openshift/aos-cd-jobs pull request #3533
Opened 2023-02-28 15:23 UTC by Ximinhan

check greenwave test status after prepare-release complete, alert in slack if there are failed greenwave test need to check

2023-02-28 15:26 UTC, Ximinhan commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +            test_result = ErrataConnector()._get(f'/api/v1/external_tests?filter[test_type]=greenwave_cvp&filter[status]=FAILED&filter[active]=true&page[size]=1000&filter[errata_id]={advisory}')
from what I see the greenwave result only valuable here, so didn't relay on elliott

2023-03-01 11:31 UTC, vfreex commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +            test_result = ErrataConnector()._get(f'/api/v1/external_tests?filter[test_type]=greenwave_cvp&filter[status]=FAILED&filter[active]=true&page[size]=1000&filter[errata_id]={advisory}')
This can be split to a separate function for better readability and easier testing.

2023-03-01 11:33 UTC, vfreex requested changes

2023-03-01 11:33 UTC, vfreex commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +        for advisory in [advisories["image"], advisories["extras"], advisories["metadata"]]:
This will cause an exception if one of the hardcoded impetus doesn't exist. What will happen if checking for all advisories with a loop?

2023-03-01 11:34 UTC, vfreex commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +from errata_tool import ErrataConnector
This needs to be defined in requirements.txt

2023-03-01 11:35 UTC, vfreex commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +        self._slack_client.bind_channel(self.release_name)
This will create another Slack thread besides the one created by Jenkinsfile. It would be nice to combine but that can be a separate PR.

2023-03-02 06:02 UTC, vfreex commented on pyartcd/pyartcd/util.py
> +def is_greenwave_all_pass_on_advisory(advisory_id: str) -> bool:
type is int.

2023-03-02 09:21 UTC, vfreex commented on pyartcd/pyartcd/pipelines/prepare_release.py
> +    def process_jira(self, jira_issue_key, jira_template_vars):
Avoid refactoring code in this PR since it is already large.

2023-03-02 10:30 UTC, Ximinhan commented
I will fix flake issue in other pr

2023-03-03 05:53 UTC, vfreex commented
@Ximinhan Let's keep this PR as simple as possible, i.e. only include the greenwave check code.
Regarding move Slack messaging logic and refactoring, please open another PRs.

2023-03-03 10:47 UTC, Ximinhan commented
ok, I will split to muti prs and test together

2023-03-06 08:32 UTC, vfreex approved these changes
/lgtm

2023-03-06 08:32 UTC, merged